a = 0.7
b = 0.8
S = 0.45
tau1 = 0.08
tau2 = 3.1
tau3 = 1.15
V_inh = -1.5
V_ex = 1.5
k = 3           # num equels in one system (one neuron model)
tMax = 500
G_ex = 0.0
G_inh = 0.0
highAccuracy = false
z1_IC = 0.01
z2_IC = 0

tMax1 = 25000
tMax2 = 10000
tMax3 = 5000

delta = 0.005   # Параметр неоднородности по а

plot_styles = [
    "--",
    "-.",
    "--",
    "dotted",
    "-.",
    "--",
    "dotted",
    "-.",
    "--",
    "dotted",
    "--",
    "-.",
    "dotted",
    "-.",
    "--",
    "dotted",
    "-.",
    "--",
    "dotted",
    "--",
    "-.",
]
scatter_markers = [
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
]
plot_colors = [
    "blue",
    "orange",
    "green",
    "red",
    "indigo",
    "m",
    "purple",
    "gray",
    "olive",
    "pink",
    "black",
    "salmon",
    "tomato",
    "navy",
    "lime",
    "orchid",
]

save_IC_data_path = "/Data/initial_conditions/"
all_graphs_save_path = "./Data/graphics"
Graphic_data_path = "./Data/graphics/fig"
unit_circle_graphs_data_path = './Data/graphics/unit_circle'
gif_data_path = './Data/gif'
pathIC = "./Data/graphics/IC.png"
path_LS = "./Data/graphics/finalState"
FHN_tr_path = "./Data/temp/FHN_coords.txt"
pathIC_test = "./Data/graphics/savedIC_test.png"

# default data paths
path_Doc_default = "./Data/results/R_Ginh"
R12_last_path_default = "./Data/temp/r12_last"
graph_R_Ginh_path_default = './Data/graphics/res_graphs/saved_fig_R_Ginh'

#for graph R(G_inh) funk

# Автоматически настраиваемые
path_Doc = "./Data/results/R_Ginh"
#path_Doc = "./Data/results/test.docx"
R12_last_path = "./Data/temp/r12_last"
graph_R_Ginh_path = './Data/graphics/res_graphs/saved_fig_R_Ginh'
#graph_R_Ginh_path = './Data/graphics/res_graphs/test.png'

# Настраиваемые
IC_type = 'prot'
G_inh_sign = -1 # -1 связь отрицательная, 1 положительная
dist_between_neurons_IC = 1
k_systems = 11   # num systems
n_streams = 10

fhn_full_animation = false
