a = 0.7
b = 0.8
S = 0.45
tau1 = 0.08
tau2 = 3.1
tau3 = 1.15
V_inh = -1.5
V_ex = 1.5
k = 3           # num equels in one system (one neuron model)
tMax = 500
G_ex = 0.0
G_inh = 0.0
highAccuracy = false
z1_IC = 0.01
z2_IC = 0

tMax1 = 10000
tMax2 = 5000
tMax3 = 3000

plot_styles = [
    "--",
    "-.",
    "--",
    "dotted",
    "-.",
    "--",
    "dotted",
    "-.",
    "--",
    "dotted",
    "--",
    "-.",
]
scatter_markers = [
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
]
plot_colors = [
    "blue",
    "orange",
    "green",
    "red",
    "indigo",
    "m",
    "yellow",
    "purple",
    "gray",
    "olive",
    "pink",
    "black",
    "salmon",
    "tomato",
    "navy",
    "gold",
    "lime",
    "orchid",
]
save_IC_data_path = "/Data/initial_conditions/"
Graphic_data_path = "./Data/graphics/fig"
pathIC = "./Data/graphics/IC.png"
path_LS = "./Data/graphics/finalState"
FHN_tr_path = "./Data/FHN_coords.txt"
pathIC_test = "./Data/graphics/savedIC_test.png"
path_Doc = "./Data/results/R_depend_Ginh_pos_10.docx"

#for graph R(G_inh) funk
G_inh_sign = 1 # -1 связь отрицательная, 1 положительная
dist_between_neurons_IC = 1
graph_R_Ginh_path = './Data/graphics/res_graphs/saved_fig_R_Ginh_pos_10.png'
k_systems = 10   # num systems
n_streams = 1

